[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["corepack enable", "corepack prepare pnpm@10.33.0 --activate"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node .output/server/index.mjs"
